# docker-compose.yml
version: "3"
services:
  server:
    build: ./server
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: production
      PORT: 3000
      MAX_DB_CONNECTIONS: ${MAX_DB_CONNECTIONS}
      SESSION_SECRET: ${SESSION_SECRET:-"super-secret"}
      KEY_SECRET: ${KEY_SECRET:-"super-secret"}
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./server/src:/app/src
      - ./server/bin:/app/bin
    networks:
      - clementine

  client:
    build: ./client
    environment:
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    stdin_open: true
    command: npm run start
    volumes:
      - ./client/src:/app/src
    networks:
      - clementine

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - clementine

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - clementine

networks:
  clementine:
    # Use a custom driver
    driver: bridge
