version: "3"
services:
  nginx:
    networks:
      - clementine
    depends_on:
      - server
      - client
    ports:
      - 8080:8080
      - 80:80
      - 443:80

  worker:
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      TRACE_THRESHOLD: ${TRACE_THRESHOLD:-500000}
    networks:
      - clementine

  server:
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 80
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      SESSION_SECRET: ${SESSION_SECRET:-"super-secret"}
      SMTP: ${SMTP}
      SMTP_EMAIL_FROM: ${SMTP_EMAIL_FROM}
      ENGINE_API_KEY: ${ENGINE_API_KEY}
    ports:
      - 80
    networks:
      - clementine

  client:
    build: ./client
    environment:
      PORT: 80
    ports:
      - 80
    networks:
      - clementine

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - clementine

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - clementine

networks:
  clementine:
    # Use a custom driver
    driver: bridge
