version: "3"
services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - clementine
    depends_on:
      - server
      - client
    ports:
      - 8080:8080
      - 80:80
      - 443:80

  worker:
    build: ./server
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      TRACE_THRESHOLD: ${TRACE_THRESHOLD:-500000}
    networks:
      - clementine

  server:
    build: ./server
    depends_on:
      - postgres
      - redis
    environment:
      DOMAIN: ${DOMAIN}
      PORT: 3000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      SESSION_SECRET: ${SESSION_SECRET}
      SMTP: ${SMTP}
      SMTP_EMAIL_FROM: ${SMTP_EMAIL_FROM}
      ENGINE_API_KEY: ${ENGINE_API_KEY}
    ports:
      - 3000
    networks:
      - clementine

  client:
    build: ./client
    environment:
      PORT: 3000
    ports:
      - 3000
    networks:
      - clementine

  postgres:
    image: postgres:10.4
    ports:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - clementine

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - clementine

networks:
  clementine:
    # Use a custom driver
    driver: bridge
