# docker-compose.yml
version: "3"
services:
  nginx:
    volumes:
      - ./nginx/user.conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      - static:/home/www-data/clementine:ro

  postgres:

  redis:

  worker:
    build:
      context: ./server
      args:
        NODE_ENV: production
    user: node
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    command: npm run start:worker
    restart: unless-stopped

  server:
    build:
      context: ./server
      args:
        NODE_ENV: production
    user: node
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    command: npm run start
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    user: node
    volumes:
      - static:/app/build
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    command: echo "mounting static!"
    restart: unless-stopped

volumes:
  static:
