# docker-compose.yml
version: "3"
services:
  nginx:
    CERTBOT_EMAIL: ${LETSENCRYPT_EMAIL}
    DOMAIN: ${DOMAIN}
    ENVSUBST_VARS: DOMAIN
    IS_STAGING: ${LETSENCRYPT_IS_STAGING:-"1"}
    volumes:
      - ./nginx/user.conf.d/${NGINX_CONF:-"prod"}.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/home/www-data/clementine:ro

  postgres:

  redis:

  worker:
    build:
      context: ./server
      args:
        NODE_ENV: production
    user: node
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    command: npm run start:worker
    restart: unless-stopped

  server:
    build:
      context: ./server
      args:
        NODE_ENV: production
    user: node
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    command: npm run start
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    user: node
    volumes:
      - static:/app/build
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    command: echo "mounting static!"

volumes:
  static:
