# docker-compose.yml
version: "3"
services:
  nginx:
    ports:
      - 443:443
    image: staticfloat/nginx-certbot
    environment:
      CERTBOT_EMAIL: ${LETSENCRYPT_EMAIL}
      DOMAIN: ${DOMAIN}
      ENVSUBST_VARS: DOMAIN
      IS_STAGING: ${LETSENCRYPT_IS_STAGING:-"1"}
    volumes:
      # nginx-certbot moves nginx.conf to ./conf.d/ and overwrites our thang
      - ./nginx/user.conf.d/ssl.conf:/etc/nginx/user.conf.d/nginx.conf:ro
      - letsencrypt:/etc/letsencrypt

  postgres:

  redis:

  worker:

  server:
    environment:
      IS_SSL: "1"

  client:

volumes:
    letsencrypt:
